const { createClient } = require('@supabase/supabase-js');
const logger = require('./logger');

// The maximum number of messages that short-term memory can retain (total number of user + assistant messages)
const SHORT_TERM_LIMIT = 20;
// Vector retrieval: Similarity threshold; memories below this value are not used.
const RAG_THRESHOLD = 0.4;
// Vector retrieval: Maximum number of relevant memories returned
const RAG_COUNT = 8;
// Only questions exceeding this value will be stored in long-term memory.
const MIN_MEMORY_LENGTH = 5;

let supabase = null;

function getSupabase() {
  if (!supabase) {
    const url = process.env.SUPABASE_URL;
    const key = process.env.SUPABASE_KEY;
    if (!url || !key) {
      throw new Error('SUPABASE_URL 或 SUPABASE_KEY 未配置');
    }
    supabase = createClient(url, key);
  }
  return supabase;
}

/**
 * This retrieves the user's recent conversation history (short-term memory), replacing the original getHistory() function.
 * @param {string} userId - Discord User ID
 * @returns {Promise<Array<{role: string, content: string}>>} - Message array sorted in chronological order
 */
async function getShortTermHistory(userId) {
  try {
    const { data, error } = await getSupabase()
      .from('app_chat_history')
      .select('role, content')
      .eq('user_id', userId)
      .order('created_at', { ascending: false })
      .limit(SHORT_TERM_LIMIT);

    if (error) throw error;

    //The database was retrieved in reverse order (latest to first), and needs to be restored to forward order before being sent to the AI.
    return (data || []).reverse();
  } catch (err) {
    logger.error('getShortTermHistory 失败:', err.message);
    return [];
  }
}

/**
 * Use gpt-4o-mini to extract user questions into keyword phrases suitable for vector retrieval.
 * Objective: To bridge the vector semantic gap between "question statements" and "declarative statements".
 * For Example："has anyone mentioned wanting to sell a car?" → "sell car vehicle"
 * @param {string} question - Original user question
 * @param {OpenAI} openai - OpenAI Client instance
 * @returns {Promise<string>} -Keyword/phrase extraction fails; revert to the original question.
 */
async function extractSearchKeywords(question, openai) {
  try {
    const response = await openai.chat.completions.create({
      model: 'gpt-4o-mini',
      messages: [
        {
          role: 'system',
          content: `You are a search keyword extractor for a community message board.
Your job: given a user's question or statement, output a short keyword phrase (3-8 words) that best represents the TOPIC being discussed, optimized for semantic similarity search against a database of past user statements.

Rules:
- Output ONLY the keyword phrase, no explanation, no punctuation at the end
- Convert questions into declarative topic phrases (e.g. "anyone selling a car?" → "selling car vehicle")
- Focus on the core subject matter: items, actions, categories (e.g. "Ford Escape 2017 sell", "looking for apartment rent")
- Strip filler words: anyone, has, someone, please, want to know, etc.
- If the message is casual chat (greetings, thanks, etc.), output: general conversation`
        },
        {
          role: 'user',
          content: question
        }
      ],
      max_tokens: 30,
      temperature: 0
    });

    const keywords = response.choices[0]?.message?.content?.trim() || '';
    if (!keywords || keywords === 'general conversation') {
      return question;
    }
    logger.debug('Keyword extraction', { original: question, keywords });
    return keywords;
  } catch (err) {
    logger.warn('Keyword extraction failed, falling back to original question:', err.message);
    return question;
  }
}

/**
 * Vectorize the keywords and retrieve the most relevant long-term memory (RAG).。
 * @param {string} keywords - Search keywords generated by the routing agent
 * @returns {Promise<{memories: Array, embedding: Array|null}>}
 */
async function searchLongTermMemories(keywords) {
  try {
    const { getClient } = require('../agents/aiClient');
    const openai = getClient();

    const embedResponse = await openai.embeddings.create({
      model: 'text-embedding-3-small',
      input: keywords
    });
    const searchEmbedding = embedResponse.data[0].embedding;
    const storeEmbedding = searchEmbedding;

    const { data: memories, error } = await getSupabase().rpc('match_memories', {
      query_embedding: searchEmbedding,
      match_threshold: RAG_THRESHOLD,
      match_count: RAG_COUNT
    });

    if (error) throw error;

    logger.debug('RAG Search Completed', { searchQuery: keywords, found: (memories || []).length });

    return { memories: memories || [], embedding: storeEmbedding };
  } catch (err) {
    logger.error('searchLongTermMemories fail:', err.message);
    return { memories: [], embedding: null };
  }
}

/**
 * Asynchronously save the current conversation to Supabase (short-term memory + long-term memory vector).
 * The caller should not await this function; instead, it should be allowed to complete silently in the background without blocking user responses.
 * @param {string} userId - Discord User ID
 * @param {string} username - Discord Username (used to let other users know who to contact)
 * @param {string} question - User's current round of questions
 * @param {string} answer - AI Answer this round
 * @param {Array|null} questionEmbedding - vector of questions（searchLongTermMemories Already generated, reuse saves costs.）
 */
async function saveMemoryAsync(userId, username, question, answer, questionEmbedding) {
  try {
    // 1. Store in the short-term memory table (one entry each for user and assistant).
    const { error: historyError } = await getSupabase()
      .from('app_chat_history')
      .insert([
        { user_id: userId, role: 'user', content: question },
        { user_id: userId, role: 'assistant', content: answer }
      ]);

    if (historyError) {
      logger.error('Short-term memory retention failure:', historyError.message);
    }

    // 2. Store the data in a long-term memory vector table (only store valuable questions, and the data must be in vector format).
    // The username is stored in the metadata, so that RAG can directly tell other users who to contact after retrieving it.
    if (question.length > MIN_MEMORY_LENGTH && questionEmbedding) {
      const { error: memoryError } = await getSupabase()
        .from('app_user_memories')
        .insert({
          user_id: userId,
          content: question,
          embedding: questionEmbedding,
          metadata: { source: 'discord', username }
        });

      if (memoryError) {
        logger.error('Failure to retain long-term memory:', memoryError.message);
      }
    }
  } catch (err) {
    logger.error('saveMemoryAsync Unexpected failure:', err.message);
  }
}

module.exports = {
  getShortTermHistory,
  searchLongTermMemories,
  saveMemoryAsync,
  extractSearchKeywords
};

//bung